# Site settings
title: https://divvv.github.io
email: nikolai.kanaev@squeed.com
description: > # this means to ignore newlines until "baseurl:"
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris non turpis eleifend, lobortis libero eget, rutrum nibh. Pellentesque eget pharetra ante. Ut non fringilla nibh, a feugiat ipsum. Ut nec lorem a est accumsan fermentum et ac augue. Nulla sit amet elementum neque. Duis id vehicula diam, ut congue tortor. Aenean luctus molestie pellentesque.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://divvv.github.io" # the base hostname & protocol for your site
twitter_username: KanaevNikolai
github_username:  Divvv
linkedin_username: nikolai-kanaev-a681b962
full_name: Nikolai Kanaev 

# Build settings
markdown: kramdown
highlighter: null
